---
- name: Install and configure apache2
  hosts: aws
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/main.yml

  roles:
    - spinup
    - apache2