---
- name: Fire up apache2, nginx, postgresql
  hosts: aws
  remote_user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  vars_files:
    - vars/main.yml

  roles:
    - spinup
    - apache2
    - nginx
    - postgres

  tasks:
   - name: check the services
     command: lsof -Pan -i tcp:80-8081
     register: lsof
   - debug: var=lsof.stdout_lines



